<?php

namespace ContainerNcruo6m;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTalkToMeCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\TalkToMeCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Command\\TalkToMeCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:talk-to-me', [], 'A self-aware command that can do... only one thing.', false, #[\Closure(name: 'App\\Command\\TalkToMeCommand')] function () use ($container): \App\Command\TalkToMeCommand {
            return ($container->privates['App\\Command\\TalkToMeCommand'] ?? $container->load('getTalkToMeCommandService'));
        });
    }
}
