<?php

namespace ContainerS1r76IP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__SAbLxpService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..SAbLxp' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..SAbLxp'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'mixRepository' => ['privates', 'App\\Repository\\VinylMixRepository', 'getVinylMixRepositoryService', true],
        ], [
            'mixRepository' => 'App\\Repository\\VinylMixRepository',
        ]);
    }
}
