<?php

namespace ContainerS1r76IP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMixControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\MixController' shared autowired service.
     *
     * @return \App\Controller\MixController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/MixController.php';

        $container->services['App\\Controller\\MixController'] = $instance = new \App\Controller\MixController();

        $instance->setContainer(($container->privates['.service_locator.yiVTbOR'] ?? $container->load('get_ServiceLocator_YiVTbORService'))->withContext('App\\Controller\\MixController', $container));

        return $instance;
    }
}
