<?php

namespace ContainerRimKrQn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSongControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\SongController' shared autowired service.
     *
     * @return \App\Controller\SongController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/SongController.php';

        $container->services['App\\Controller\\SongController'] = $instance = new \App\Controller\SongController();

        $instance->setContainer(($container->privates['.service_locator.yiVTbOR'] ?? $container->load('get_ServiceLocator_YiVTbORService'))->withContext('App\\Controller\\SongController', $container));

        return $instance;
    }
}
