<?php

namespace ContainerRimKrQn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVinylControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\VinylController' shared autowired service.
     *
     * @return \App\Controller\VinylController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/VinylController.php';

        $container->services['App\\Controller\\VinylController'] = $instance = new \App\Controller\VinylController(true, ($container->privates['App\\Service\\MixRepository'] ?? $container->load('getMixRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.yiVTbOR'] ?? $container->load('get_ServiceLocator_YiVTbORService'))->withContext('App\\Controller\\VinylController', $container));

        return $instance;
    }
}
