<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXskwXqo\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXskwXqo/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXskwXqo.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXskwXqo\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXskwXqo\App_KernelDevDebugContainer([
    'container.build_hash' => 'XskwXqo',
    'container.build_id' => 'a25c5bf1',
    'container.build_time' => 1676629306,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXskwXqo');
