<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNcruo6m\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNcruo6m/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNcruo6m.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNcruo6m\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNcruo6m\App_KernelDevDebugContainer([
    'container.build_hash' => 'Ncruo6m',
    'container.build_id' => 'b1a0bd5b',
    'container.build_time' => 1675947886,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNcruo6m');
