<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerS1r76IP\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerS1r76IP/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerS1r76IP.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerS1r76IP\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerS1r76IP\App_KernelDevDebugContainer([
    'container.build_hash' => 'S1r76IP',
    'container.build_id' => 'a7cd997c',
    'container.build_time' => 1676575014,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerS1r76IP');
